accounts/urls.py
from . import views
from django.urls import path


app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('admin-login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

myapp/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView


app_name = 'myapp'
urlpatterns = [
    path('', TemplateView.as_view(template_name='myapp/home.html'), name='home'),
    path('user-home/', views.UserHomeView.as_view(), name='user_home'),
    path('admin-home/', views.AdminHomeView.as_view(), name='admin_home'),
    path('user-profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('user-points/', views.UserPointsView.as_view(), name='user_points'),
    path('task-create/<int:app_id>/', views.TaskCreateView.as_view(), name='task_create'),
    path('tasks-claimed/', views.TaskClaimedView.as_view(), name='task_claimed'),
    path('application-create/', 
        views.ApplicationCreateView.as_view(), 
        name='application_create'
    ),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Application(models.Model):
    PROGRAMMING = 'PR'
    SPORTS = 'SP'
    HEALTH = 'HE'
    TRAVEL = 'TR'
    ENTERTAINMENT = 'EN'
    CATEGORY_CHOICES = [
        (PROGRAMMING, 'Programming'),
        (SPORTS, 'Sports'),
        (HEALTH, 'Health'),
        (TRAVEL, 'Travel'),
        (ENTERTAINMENT, 'Entertainment'),
    ]
    name = models.CharField(max_length=40)
    url = models.URLField()
    category = models.CharField(
        max_length=2,
        choices=CATEGORY_CHOICES,
        default=PROGRAMMING,
    )
    points = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'{self.name}'


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='tasks')

    def __str__(self):
        return f'{self.user.username}-{self.application.name}'

myapp/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('image',)

myapp/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import CreateView, ListView
from django.views.generic.base import TemplateView

from .forms import TaskForm
from .models import Application, Task
from .utils import get_user_points


@method_decorator(staff_member_required(login_url='accounts:admin_login'), name='dispatch')
class ApplicationCreateView(CreateView):
    model = Application
    fields = '__all__'
    success_url = reverse_lazy('myapp:admin_home')
    template_name = 'myapp/application_create.html'


@method_decorator(staff_member_required(login_url='accounts:admin_login'), name='dispatch')
class AdminHomeView(ListView):
    model = Application
    context_object_name = 'apps'
    template_name = 'myapp/admin_home.html'


@method_decorator(login_required, name='dispatch')
class UserHomeView(ListView):
    context_object_name = 'apps'
    template_name = 'myapp/user_home.html'

    def get_queryset(self):
        claimed_apps_id = list(
            Task.objects.filter(user=self.request.user).
            values_list('application_id', flat=True)
        )
        not_claimed_apps = Application.objects.exclude(id__in=claimed_apps_id)
        return not_claimed_apps


@method_decorator(login_required, name='dispatch')
class UserProfileView(TemplateView):
    template_name = "myapp/user_profile.html"


@method_decorator(login_required, name='dispatch')
class UserPointsView(View):
    def get(self, request, *args, **kwargs):
        points = get_user_points(request.user)
        context = {
            'points': points
        }
        return render(request, "myapp/user_points.html", context)


@method_decorator(login_required, name='dispatch')
class TaskCreateView(View):
    form_class = TaskForm
    template_name = 'myapp/task_create.html'

    def get_context_data(self, **kwargs):
        app_id = self.kwargs['app_id']
        app = Application.objects.get(id=app_id)
        context = {
            'app': app,
            'form': self.form_class
        }
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        user = self.request.user
        context = self.get_context_data(**kwargs)
        app = context['app']
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            img = form.cleaned_data['image']
            fs = FileSystemStorage()
            image = fs.save(img.name, img)
            task = Task.objects.create(user=user, application=app, image=image)
            return redirect(reverse('myapp:user_home'))
        return render(request, self.template_name, context)
    

@method_decorator(login_required, name='dispatch')
class TaskClaimedView(ListView):
    context_object_name = 'tasks'
    template_name = 'myapp/tasks_claimed.html'

    def get_queryset(self):
        user = self.request.user
        queryset = Task.objects.filter(user=user)
        return queryset

myapp/templates/myapp/admin_home.html
<html>
  <h1>Welcome Admin!</h1>
  <a href="{% url 'myapp:application_create' %}">Add New App</a>
  <br />
  <a href="{% url 'accounts:logout' %}">Logout</a>
  <br>
  <h3>Application List</h3>
  {% for app in apps %}
    SN: {{ forloop.counter }}
    <br>
    Name: {{ app.name }}
    <br>
    Url: <a href="{{ app.url }}">{{ app.url }}</a>
    <br>
    Category: {{ app.get_category_display }}
    <br>
    Points: {{ app.points }}
    <hr>
  {% endfor %}
</html>

myapp/templates/myapp/application_create.html
<a href="{% url 'myapp:admin_home' %}"><< Home</a>
<br>
<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

myapp/templates/myapp/home.html
<html>
  <h1>Welcome!</h1>
  <a href="{% url 'accounts:register' %}">User Registration</a>
  <br />
  <a href="{% url 'accounts:login' %}">User Login</a>
  <br />
  <a href="{% url 'accounts:admin_login' %}">Admin Login</a>
</html>

myapp/templates/myapp/task_create.html
<html>
    <a href="{% url 'myapp:user_home' %}"><< Home</a>
    <br><br>
    <p>Name: {{ app.name }}</p>
    <p>Url: <a href="{{ app.url }}">{{ app.url }}</a></p>
    <p>Points: {{ app.points }}</p>
    <p>Upload screenshot to claim points.</p>
    <br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <br>
        <input type="submit" value="Upload" />
    </form>
</html>

myapp/templates/myapp/tasks_claimed.html
<html>
    <a href="{% url 'myapp:user_home' %}"><< Home</a>
    <h1>Claimed tasks</h1>
    {% for task in tasks %}
        SN: {{ forloop.counter }}
        <br>
        App Name: {{ task.application.name }}
        <br>
        App Url: <a href="{{ task.application.url }}">{{ task.application.url }}</a>
        <br>
        Points Obtained: {{ task.application.points }}
        <br>
        ScreenShot Uploaded: <a href="{{ task.image.url}}">ScreenShot</a>
        <hr>
        {% empty %}
        <p>Sorry, no tasks claimed till now</p>  
    {% endfor %}    
</html>

myapp/templates/myapp/user_home.html
<html>
  <h1>Hello {{ user.username }}!</h1>
  <a href="{% url 'myapp:user_profile' %}">Profile</a>
  <br />
  <a href="{% url 'myapp:user_points' %}">Points</a>
  <br />
  <a href="{% url 'myapp:task_claimed' %}">Tasks</a>
  <br>
  <a href="{% url 'accounts:logout' %}">Logout</a>
  <br />
  <h1>Applications to claim</h1>
  {% for app in apps %}
      SN: {{ forloop.counter }}
      <br>
      Name: {{ app.name }}
      <br>
      Url: <a href="{{ app.url }}">{{ app.url }}</a>
      <br>
      Category: {{ app.get_category_display }}
      <br>
      Points: {{ app.points }}
      <br>
      <a href="{% url 'myapp:task_create' app.id %}">View in Detail</a>
      <hr>
      {% empty %}
      <p>Sorry, no Apps left to claim</p>
  {% endfor %}
</html>

myapp/templates/myapp/user_points.html
<html>
  <a href="{% url 'myapp:user_home' %}"><< Home</a>
  <br>
  <h1>Points Earned</h1>
  {% if points != 0 %}
  <p>Congrats {{user.username}}! You have total {{points}} points.</p>
  {% else %}
  <p>Sorry {{user.username}} You have {{points}} points.</p>
  {% endif %}
  </html>

myapp/templates/myapp/user_profile.html
<html>
  <a href="{% url 'myapp:user_home' %}"><< Home</a>
  <p>Username: {{ user.username }}</p>
  <p>First Name: {{ user.first_name }}</p>
  <p>Last Name: {{ user.last_name }}</p>
  <p>Email: {{ user.email }}</p>
</html>